### ISSUE TITLE
issue with property check statement.

### ISSUE THREAD

**Issue by caoer** [jin5354/leaf-observable#2]
For code in: https://github.com/jin5354/leaf-observable/blob/master/src/observable.js#L150
There are a few other cases in the lib. simply check for `if(target[key])` is not enough. considering following case. 

> const a = {'k': ''}
undefined
> a.k
''
> a
{ k: '' }
> a.k == true
false
> a.k == false
true
> a.k = '1'
'1'
> a.k == false
false
> a.k == true
true

**Comment by jin5354** [comment]
Now using Object.prototype.hasOwnProperty to check. Thankyou.

**Comment by caoer** [comment]
👍
